"""core#137: the editor's collapse output executes exactly like the flat graph.

``fixtures/subgraph_contract.json`` is GENERATED by the frontend's own collapse
(``frontend/src/utils/subgraph.contract.test.ts``), so what runs here is what
the editor actually produces -- not a second hand-written fixture that would
only ever agree with the first one.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.core.codegen import generate_python
from app.core.graph_engine import execute_graph, validate_graph

FIXTURE = Path(__file__).parent / "fixtures" / "subgraph_contract.json"


@pytest.fixture(scope="module")
def contract() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _outputs(results: dict, node_id: str, port: str) -> float:
    return float(results[node_id][port].reshape(-1)[0])


def test_the_fixture_is_the_editors_own_collapse(contract):
    """Sanity: the generated half really is a collapsed graph.

    Guards against a regeneration that silently wrote the flat graph back --
    the equivalence assertions below would then compare a graph with itself
    and pass while proving nothing.
    """
    collapsed = contract["collapsed"]
    assert collapsed["subgraphs"], "fixture has no subgraph definitions"
    instances = [
        n for n in collapsed["nodes"] if str(n["type"]).startswith("subgraph:")
    ]
    assert len(instances) == 1
    inner_ids = {n["id"] for n in collapsed["subgraphs"][0]["nodes"]}
    assert inner_ids == set(contract["selection"])
    # The selected nodes are GONE from the top level.
    assert not (inner_ids & {n["id"] for n in collapsed["nodes"]})


async def test_collapsed_and_flat_graphs_compute_the_same_numbers(contract):
    """Acceptance criterion 1, end to end across both layers."""
    flat = contract["flat"]
    collapsed = contract["collapsed"]

    flat_results = await execute_graph(flat["nodes"], flat["edges"])
    collapsed_results = await execute_graph(
        collapsed["nodes"],
        collapsed["edges"],
        subgraphs=collapsed["subgraphs"],
    )

    # 2*5 + 3*7 = 31, averaged over a row of two equal values.
    assert _outputs(flat_results, "avg", "tensor") == pytest.approx(31.0)
    assert _outputs(collapsed_results, "avg", "tensor") == pytest.approx(
        _outputs(flat_results, "avg", "tensor")
    )

    # The collapsed run really did cross a boundary: its inner nodes carry
    # namespaced ids the flat run does not have, and vice versa.
    assert "blk/sum" in collapsed_results
    assert "sum" in flat_results and "sum" not in collapsed_results


def test_both_halves_validate_clean(contract):
    flat, collapsed = contract["flat"], contract["collapsed"]
    assert validate_graph(flat["nodes"], flat["edges"]) == []
    assert validate_graph(
        collapsed["nodes"], collapsed["edges"],
        subgraphs=collapsed["subgraphs"],
    ) == []


def test_the_collapsed_graph_exports_a_runnable_script(contract):
    collapsed = contract["collapsed"]
    script = generate_python(
        collapsed["nodes"], collapsed["edges"],
        name="Contract", subgraphs=collapsed["subgraphs"],
    )
    compile(script, "<contract>", "exec")
    assert "def subgraph_combine(" in script
    assert "subgraph:combine" not in script


# ── The 60-node demo (acceptance criterion 3) ───────────────────────────


def test_the_demo_collapses_sixty_nodes_into_four_boxes(contract):
    demo = contract["demo60"]
    assert len(demo["flat"]["nodes"]) == 60
    assert len(demo["collapsed"]["subgraphs"]) == 4
    instances = [
        n for n in demo["collapsed"]["nodes"]
        if str(n["type"]).startswith("subgraph:")
    ]
    assert len(instances) == 4
    assert len(demo["collapsed"]["nodes"]) == 12


async def test_the_collapsed_demo_still_runs_and_agrees_with_the_flat_one(
    contract,
):
    demo = contract["demo60"]
    flat = await execute_graph(demo["flat"]["nodes"], demo["flat"]["edges"])
    collapsed = await execute_graph(
        demo["collapsed"]["nodes"],
        demo["collapsed"]["edges"],
        subgraphs=demo["collapsed"]["subgraphs"],
    )
    # Four branches seeded 1..4, each multiplied by 1 thirteen times, summed.
    assert _outputs(flat, "sum3", "tensor") == pytest.approx(10.0)
    assert _outputs(collapsed, "sum3", "tensor") == _outputs(
        flat, "sum3", "tensor"
    )
    # 52 of the 60 nodes now run behind a boundary.
    namespaced = [nid for nid in collapsed if "/" in nid]
    assert len(namespaced) == 52


def test_the_collapsed_demo_exports_four_subgraph_functions(contract):
    demo = contract["demo60"]
    script = generate_python(
        demo["collapsed"]["nodes"], demo["collapsed"]["edges"],
        name="Demo60", subgraphs=demo["collapsed"]["subgraphs"],
    )
    compile(script, "<demo60>", "exec")
    for index in range(4):
        assert f"def subgraph_blk{index}(" in script
