"""core#137: the editor's collapse output executes exactly like the flat graph.

``fixtures/subgraph_contract.json`` is GENERATED by the frontend's own collapse
(``frontend/src/utils/subgraph.contract.test.ts``), so what runs here is what
the editor actually produces -- not a second hand-written fixture that would
only ever agree with the first one.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.core.codegen import generate_python
from app.core.graph_engine import (
    build_subgraph_index,
    execute_graph,
    expand_subgraphs_deep,
    validate_graph,
)

FIXTURE = Path(__file__).parent / "fixtures" / "subgraph_contract.json"


@pytest.fixture(scope="module")
def contract() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _outputs(results: dict, node_id: str, port: str) -> float:
    return float(results[node_id][port].reshape(-1)[0])


def test_the_fixture_is_the_editors_own_collapse(contract):
    """Sanity: the generated half really is a collapsed graph.

    Guards against a regeneration that silently wrote the flat graph back --
    the equivalence assertions below would then compare a graph with itself
    and pass while proving nothing.
    """
    collapsed = contract["collapsed"]
    assert collapsed["subgraphs"], "fixture has no subgraph definitions"
    instances = [
        n for n in collapsed["nodes"] if str(n["type"]).startswith("subgraph:")
    ]
    assert len(instances) == 1
    inner_ids = {n["id"] for n in collapsed["subgraphs"][0]["nodes"]}
    assert inner_ids == set(contract["selection"])
    # The selected nodes are GONE from the top level.
    assert not (inner_ids & {n["id"] for n in collapsed["nodes"]})


async def test_collapsed_and_flat_graphs_compute_the_same_numbers(contract):
    """Acceptance criterion 1, end to end across both layers."""
    flat = contract["flat"]
    collapsed = contract["collapsed"]

    flat_results = await execute_graph(flat["nodes"], flat["edges"])
    collapsed_results = await execute_graph(
        collapsed["nodes"],
        collapsed["edges"],
        subgraphs=collapsed["subgraphs"],
    )

    # 2*5 + 3*7 = 31, averaged over a row of two equal values.
    assert _outputs(flat_results, "avg", "tensor") == pytest.approx(31.0)
    assert _outputs(collapsed_results, "avg", "tensor") == pytest.approx(
        _outputs(flat_results, "avg", "tensor")
    )

    # The collapsed run really did cross a boundary: its inner nodes carry
    # namespaced ids the flat run does not have, and vice versa. Named on an
    # inner node rather than on the count of them, so this stays a statement
    # about the boundary even if the selection is widened later.
    assert "blk/m1" in collapsed_results
    assert "m1" in flat_results and "m1" not in collapsed_results
    # `sum` is deliberately OUTSIDE the block: it is what consumes both of the
    # block's outputs, which is what puts two same-named boundary ports on the
    # interface (see the port-name test below).
    assert "sum" in collapsed_results and "sum" in flat_results


def test_the_trigger_crosses_the_boundary_onto_the_right_inner_node(contract):
    """The trigger fan-out, checked STRUCTURALLY -- execution cannot see it.

    In the flat graph Start triggers ``a``; ``a`` is inside the block, so
    collapse rewrote that edge to point at the instance (``t1-sg``) and
    recorded ``a`` in ``interface.triggerTargets``. Expansion has to put it
    back on ``blk/a`` and nowhere else.

    This does NOT fall out of the equivalence test above, which is why it is
    written separately rather than trusted to it. Trigger edges are excluded
    from in-degree, so they never influence the topological order -- they only
    pick entry points, and reachability from those entry points is then widened
    again by the container rule that retains every node inside a block once ANY
    node in that block is reachable. ``b`` feeds ``blk/m2`` with a plain data
    edge, so the whole block stays executable no matter where its trigger
    lands. Measured, not assumed: retargeting this edge at ``blk/sum`` or at
    ``blk/m2``, and deleting it outright, each still produce avg == 31.0 with
    all seven nodes run. Every one of those is a broken editor, and only an
    assertion on the expanded SHAPE catches them.
    """
    collapsed = contract["collapsed"]
    definition = collapsed["subgraphs"][0]
    # What the editor recorded at collapse. Pinned by id, not merely non-empty:
    # the fan-out is only correct if it names the node Start actually triggered.
    assert definition["interface"]["triggerTargets"] == ["a"]

    nodes, edges, _ = expand_subgraphs_deep(
        collapsed["nodes"],
        collapsed["edges"],
        build_subgraph_index(collapsed["subgraphs"]),
    )
    instance = contract["instanceId"]
    # No trigger may still be addressed to the instance: it is gone from the
    # expanded graph, so an edge naming it is an edge into nothing.
    assert not [
        e for e in edges
        if e.get("type") == "trigger" and instance in (e["source"], e["target"])
    ]
    fanned = sorted(
        e["target"] for e in edges
        if e.get("type") == "trigger" and e["target"].startswith(f"{instance}/")
    )
    assert fanned == ["blk/a"]

    # And the OUTSIDE trigger is untouched: `b` was not in the selection, so
    # Start still reaches it directly. A rewrite that swallowed every trigger
    # into the block would otherwise satisfy the assertion above.
    assert [
        e["target"] for e in edges
        if e.get("type") == "trigger" and not e["target"].startswith(f"{instance}/")
    ] == ["b"]


def test_the_two_same_named_outputs_route_to_their_own_inner_nodes(contract):
    """The renamed boundary port, checked STRUCTURALLY -- for the same reason.

    ``m1`` and ``m2`` both leave the block on a handle called ``tensor``, so
    collapse renamed the second to ``tensor_2``. Those names are the ONLY thing
    the outer edges carry; expansion resolves each back to an inner node
    through ``interface.outputs``. If the two sides ever disagreed about which
    name belongs to which inner node, the edge into ``sum.tensor_a`` would come
    from ``m2`` and the one into ``sum.tensor_b`` from ``m1``.

    The equivalence test cannot see that swap. The consumer is an Add, and
    10 + 21 == 21 + 10, so the run still lands on 31.0 with the wires crossed.
    """
    collapsed = contract["collapsed"]
    ports = collapsed["subgraphs"][0]["interface"]["outputs"]
    assert [p["port"] for p in ports] == ["tensor", "tensor_2"]

    nodes, edges, _ = expand_subgraphs_deep(
        collapsed["nodes"],
        collapsed["edges"],
        build_subgraph_index(collapsed["subgraphs"]),
    )
    into_sum = {
        e["targetHandle"]: (e["source"], e["sourceHandle"])
        for e in edges
        if e["target"] == "sum"
    }
    # m1 has scalar 5 and m2 has scalar 7, so this is also the only wiring that
    # makes the flat graph's tensor_a/tensor_b assignment survive collapse.
    assert into_sum == {
        "tensor_a": ("blk/m1", "tensor"),
        "tensor_b": ("blk/m2", "tensor"),
    }


def test_both_halves_validate_clean(contract):
    flat, collapsed = contract["flat"], contract["collapsed"]
    assert validate_graph(flat["nodes"], flat["edges"]) == []
    assert validate_graph(
        collapsed["nodes"], collapsed["edges"],
        subgraphs=collapsed["subgraphs"],
    ) == []


def test_the_collapsed_graph_exports_a_runnable_script(contract):
    collapsed = contract["collapsed"]
    script = generate_python(
        collapsed["nodes"], collapsed["edges"],
        name="Contract", subgraphs=collapsed["subgraphs"],
    )
    compile(script, "<contract>", "exec")
    assert "def subgraph_combine(" in script
    assert "subgraph:combine" not in script


# ── The 60-node demo (acceptance criterion 3) ───────────────────────────


def test_the_demo_collapses_sixty_nodes_into_four_boxes(contract):
    demo = contract["demo60"]
    assert len(demo["flat"]["nodes"]) == 60
    assert len(demo["collapsed"]["subgraphs"]) == 4
    instances = [
        n for n in demo["collapsed"]["nodes"]
        if str(n["type"]).startswith("subgraph:")
    ]
    assert len(instances) == 4
    assert len(demo["collapsed"]["nodes"]) == 12


async def test_the_collapsed_demo_still_runs_and_agrees_with_the_flat_one(
    contract,
):
    demo = contract["demo60"]
    flat = await execute_graph(demo["flat"]["nodes"], demo["flat"]["edges"])
    collapsed = await execute_graph(
        demo["collapsed"]["nodes"],
        demo["collapsed"]["edges"],
        subgraphs=demo["collapsed"]["subgraphs"],
    )
    # Four branches seeded 1..4, each multiplied by 1 thirteen times, summed.
    assert _outputs(flat, "sum3", "tensor") == pytest.approx(10.0)
    assert _outputs(collapsed, "sum3", "tensor") == _outputs(
        flat, "sum3", "tensor"
    )
    # 52 of the 60 nodes now run behind a boundary.
    namespaced = [nid for nid in collapsed if "/" in nid]
    assert len(namespaced) == 52


def test_the_collapsed_demo_exports_four_subgraph_functions(contract):
    demo = contract["demo60"]
    script = generate_python(
        demo["collapsed"]["nodes"], demo["collapsed"]["edges"],
        name="Demo60", subgraphs=demo["collapsed"]["subgraphs"],
    )
    compile(script, "<demo60>", "exec")
    for index in range(4):
        assert f"def subgraph_blk{index}(" in script
