/**
 * The Inspector's recovery from a too-large tensor, against the server's own
 * answers (#640).
 *
 * `backend/tests/fixtures/bounded_preview_contract.json` is GENERATED by
 * `backend/tests/test_bounded_tensor_preview.py` from the live route: the 413
 * a full read of a [2, 3, 5] tensor gets at a limit of 12, and the bounded
 * preview the same tensor gets with `preview=true`. Here the real
 * `fetchOutput` reads them through a stubbed `fetch` that answers by URL, so
 * a client that asks for anything else -- the old fixed `0,:,:` retry, say --
 * gets the 400 the server sends and the test fails.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { act, render, screen } from '@testing-library/react';

import { useI18n } from '../../i18n';
import type { TensorOutput } from '../../types';
import { fetchPortWithSliceFallback, PREVIEW_MAX_ELEMENTS } from './portCaptures';
import { TensorGridView } from './TensorGridView';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.resolve(
  HERE,
  '../../../../backend/tests/fixtures/bounded_preview_contract.json',
);

interface Answer {
  status: number;
  body: unknown;
}
const contract = JSON.parse(readFileSync(FIXTURE, 'utf-8')) as {
  refused: Answer;
  preview: Answer;
};

function respond({ status, body }: Answer): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    statusText: 'mock',
    json: async () => body,
  } as unknown as Response;
}

const g = globalThis as unknown as { fetch: typeof fetch };
let originalFetch: typeof fetch;
let urls: URL[];

beforeEach(() => {
  originalFetch = g.fetch;
  urls = [];
  g.fetch = vi.fn(async (input: RequestInfo | URL) => {
    const url = new URL(String(input), 'http://localhost');
    urls.push(url);
    const q = url.searchParams;
    if (q.get('preview') === 'true' && !q.has('slice')) return respond(contract.preview);
    if (!q.has('slice')) return respond(contract.refused);
    return respond({ status: 400, body: { detail: 'slice failed: too many indices' } });
  }) as unknown as typeof fetch;
});

afterEach(() => {
  g.fetch = originalFetch;
  act(() => useI18n.setState({ locale: 'en' }));
});

describe('bounded tensor preview, against the server contract', () => {
  it('recovers from the refusal with the preview the server picks', async () => {
    expect(contract.refused.status).toBe(413);

    const data = (await fetchPortWithSliceFallback('run1', 'a', 'out')) as TensorOutput;

    expect(urls).toHaveLength(2);
    expect(urls[1].searchParams.get('preview')).toBe('true');
    expect(urls[1].searchParams.get('max_elements')).toBe(String(PREVIEW_MAX_ELEMENTS));
    expect(data).toEqual(contract.preview.body);
    expect(data.truncated).toBe(true);
  });

  it('shows the full shape and names the part shown', async () => {
    const data = (await fetchPortWithSliceFallback('run1', 'a', 'out')) as TensorOutput;
    const { container } = render(<TensorGridView tensor={data} />);

    expect(screen.getByText('shape [2, 3, 5]')).toBeInTheDocument();
    expect(
      screen.getByText('Preview: slice [0, 0:2] · shape [2, 5] · 10 of 30 values'),
    ).toBeInTheDocument();
    // The stats sit with the part they describe, not with the full shape.
    const note = screen.getByText(/^Preview:/).parentElement!;
    expect(note.textContent).toContain('min 0');
    expect(container.querySelector('[class*="tensorMeta"]')!.textContent).not.toContain('min');
    expect(container.querySelectorAll('td')).toHaveLength(10);
  });

  it('says the same in zh-TW', async () => {
    act(() => useI18n.setState({ locale: 'zh-TW' }));
    const data = (await fetchPortWithSliceFallback('run1', 'a', 'out')) as TensorOutput;
    render(<TensorGridView tensor={data} />);

    expect(
      screen.getByText('預覽：切片 [0, 0:2] · 形狀 [2, 5] · 共 30 個值，顯示 10 個'),
    ).toBeInTheDocument();
  });
});
