/**
 * The frontend/backend subgraph contract (core#137).
 *
 * `backend/tests/fixtures/subgraph_contract.json` holds one graph twice: flat,
 * and with three nodes collapsed. THIS test proves the collapsed half is what
 * the editor's own collapse produces; `backend/tests/test_subgraph_contract.py`
 * proves both halves EXECUTE to the same numbers.
 *
 * Two hand-written fixtures on either side of the boundary would agree with
 * each other and with nothing else. One shared file, generated by one side and
 * executed by the other, is what makes "collapse changes nothing about what
 * the graph computes" a claim about the shipped code.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { describe, it, expect, beforeEach } from 'vitest';
import type { Edge, Node } from '@xyflow/react';

import { useTabStore } from '../store/tabStore';
import type { NodeData, NodeDefinition } from '../types';
import { collapseSelection } from './subgraph';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.resolve(
  HERE,
  '../../../backend/tests/fixtures/subgraph_contract.json',
);

/** Port sets for the node types the fixture uses, as the backend declares them. */
const PORTS: Record<string, { inputs: string[]; outputs: string[] }> = {
  Start: { inputs: [], outputs: ['trigger'] },
  TensorCreate: { inputs: [], outputs: ['tensor'] },
  ScalarMultiply: { inputs: ['tensor'], outputs: ['tensor'] },
  Add: { inputs: ['tensor_a', 'tensor_b'], outputs: ['tensor'] },
  Mean: { inputs: ['tensor'], outputs: ['tensor'] },
};

function definitionFor(type: string): NodeDefinition {
  const spec = PORTS[type] ?? { inputs: [], outputs: [] };
  return {
    node_name: type,
    category: 'x',
    description: '',
    inputs: spec.inputs.map((name) => ({
      name, data_type: 'TENSOR', description: '', optional: false,
    })),
    outputs: spec.outputs.map((name) => ({
      name, data_type: name === 'trigger' ? 'TRIGGER' : 'TENSOR',
      description: '', optional: false,
    })),
    params: [],
  };
}

function toCanvas(raw: any[]): Node<NodeData>[] {
  return raw.map((n) => ({
    id: n.id,
    type: n.type === 'Start' ? 'start' : 'baseNode',
    position: n.position,
    data: {
      label: n.id,
      type: n.type,
      params: n.data?.params ?? {},
      definition: definitionFor(n.type),
      executionStatus: 'idle' as const,
    },
  }));
}

function toCanvasEdges(raw: any[]): Edge[] {
  return raw.map((e) =>
    e.type === 'trigger'
      ? {
          id: e.id, source: e.source, target: e.target,
          sourceHandle: e.sourceHandle, targetHandle: e.targetHandle,
          type: 'triggerEdge', data: { type: 'trigger' },
        }
      : {
          id: e.id, source: e.source, target: e.target,
          sourceHandle: e.sourceHandle, targetHandle: e.targetHandle,
        },
  );
}

const store = () => useTabStore.getState();

beforeEach(() => {
  useTabStore.setState({ tabs: [], activeTabId: null as unknown as string });
  store().addTab('contract');
});

describe('subgraph collapse contract', () => {
  it('produces exactly the collapsed graph the backend suite executes', () => {
    const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));

    store().setNodes(toCanvas(fixture.flat.nodes));
    store().setEdges(toCanvasEdges(fixture.flat.edges));

    // The pure collapse with the fixture's ids pinned; everything else --
    // boundary derivation, rewiring, serialization -- is the shipped path.
    const result = collapseSelection(
      store().getActiveTab().nodes,
      store().getActiveTab().edges,
      [],
      fixture.selection,
      { id: fixture.subgraphId, instanceId: fixture.instanceId, name: fixture.name },
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    store().setNodes(result.nodes);
    store().setEdges(result.edges);
    store().setSubgraphs(result.subgraphs);

    const serialized = JSON.parse(JSON.stringify(store().getSerializedGraph()));

    // Regenerate the fixture with
    //   CODEFYUI_WRITE_SUBGRAPH_FIXTURE=1 pnpm exec vitest run \
    //     src/utils/subgraph.contract.test.ts
    // then re-run the backend suite: the point of the file is that the two
    // halves execute alike, so a regenerated fixture is only correct once
    // `backend/tests/test_subgraph_contract.py` has agreed with it.
    if (process.env.CODEFYUI_WRITE_SUBGRAPH_FIXTURE) {
      fixture.collapsed = {
        nodes: serialized.nodes,
        edges: serialized.edges,
        subgraphs: serialized.subgraphs,
      };
      writeFileSync(FIXTURE, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
    }

    const sortById = (rows: any[]) =>
      [...rows].sort((a, b) => String(a.id).localeCompare(String(b.id)));

    expect(sortById(serialized.nodes)).toEqual(sortById(fixture.collapsed.nodes));
    expect(sortById(serialized.edges)).toEqual(sortById(fixture.collapsed.edges));
    expect(serialized.subgraphs).toEqual(fixture.collapsed.subgraphs);
  });

  it('collapses a 60-node demo into four boxes', () => {
    // Acceptance criterion 3. Four independent branches of thirteen
    // multiplies each, summed at the end; every branch's chain becomes one
    // block. The backend suite runs the result and checks the number.
    const nodes: any[] = [
      { id: 'start', type: 'Start', position: { x: 0, y: 0 }, data: { params: {} } },
    ];
    const edges: any[] = [];
    const branchTails: string[] = [];
    const groups: string[][] = [];

    for (let branch = 0; branch < 4; branch += 1) {
      const y = branch * 200;
      const root = `src${branch}`;
      nodes.push({
        id: root, type: 'TensorCreate', position: { x: 100, y },
        data: { params: { shape: '1,2', fill: 'full', value: branch + 1 } },
      });
      edges.push({
        id: `t${branch}`, source: 'start', target: root,
        sourceHandle: 'trigger', targetHandle: '__trigger', type: 'trigger',
      });
      const chain: string[] = [];
      let previous = root;
      let previousPort = 'tensor';
      for (let step = 0; step < 13; step += 1) {
        const id = `b${branch}m${step}`;
        nodes.push({
          id, type: 'ScalarMultiply',
          position: { x: 220 + step * 90, y },
          data: { params: { scalar: 1 } },
        });
        edges.push({
          id: `e${branch}_${step}`, source: previous, target: id,
          sourceHandle: previousPort, targetHandle: 'tensor',
        });
        chain.push(id);
        previous = id;
        previousPort = 'tensor';
      }
      groups.push(chain);
      branchTails.push(previous);
    }

    // 4 branches -> 3 Adds: 1 + 4*(1 + 13) + 3 = 60 nodes.
    let running = branchTails[0];
    for (let index = 1; index < 4; index += 1) {
      const id = `sum${index}`;
      nodes.push({
        id, type: 'Add', position: { x: 1500, y: index * 200 },
        data: { params: { alpha: 1 } },
      });
      edges.push({
        id: `sa${index}`, source: running, target: id,
        sourceHandle: 'tensor', targetHandle: 'tensor_a',
      });
      edges.push({
        id: `sb${index}`, source: branchTails[index], target: id,
        sourceHandle: 'tensor', targetHandle: 'tensor_b',
      });
      running = id;
    }
    expect(nodes).toHaveLength(60);

    store().setNodes(toCanvas(nodes));
    store().setEdges(toCanvasEdges(edges));

    groups.forEach((chain, index) => {
      const current = store().getActiveTab();
      const result = collapseSelection(
        current.nodes, current.edges, current.subgraphs, chain,
        { id: `blk${index}`, instanceId: `inst${index}`, name: `Branch ${index}` },
      );
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      store().setNodes(result.nodes);
      store().setEdges(result.edges);
      store().setSubgraphs(result.subgraphs);
    });

    const serialized = JSON.parse(JSON.stringify(store().getSerializedGraph()));
    expect(serialized.subgraphs).toHaveLength(4);
    expect(
      serialized.nodes.filter((n: any) => String(n.type).startsWith('subgraph:')),
    ).toHaveLength(4);
    // 60 nodes minus the 52 that moved inside, plus 4 boxes.
    expect(serialized.nodes).toHaveLength(12);

    if (process.env.CODEFYUI_WRITE_SUBGRAPH_FIXTURE) {
      const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));
      fixture.demo60 = {
        flat: { nodes, edges },
        collapsed: {
          nodes: serialized.nodes,
          edges: serialized.edges,
          subgraphs: serialized.subgraphs,
        },
      };
      writeFileSync(FIXTURE, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
    }
  });
});
