/**
 * The frontend/backend subgraph contract (core#137).
 *
 * `backend/tests/fixtures/subgraph_contract.json` holds one graph twice: flat,
 * and with three nodes collapsed. THIS test proves the collapsed half is what
 * the editor's own collapse produces; `backend/tests/test_subgraph_contract.py`
 * proves both halves EXECUTE to the same numbers.
 *
 * Two hand-written fixtures on either side of the boundary would agree with
 * each other and with nothing else. One shared file, generated by one side and
 * executed by the other, is what makes "collapse changes nothing about what
 * the graph computes" a claim about the shipped code.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { describe, it, expect, beforeEach } from 'vitest';
import type { Edge, Node } from '@xyflow/react';

import { useTabStore } from '../store/tabStore';
import type { NodeData, NodeDefinition } from '../types';
import { collapseSelection } from './subgraph';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.resolve(
  HERE,
  '../../../backend/tests/fixtures/subgraph_contract.json',
);

/** Port sets for the node types the fixture uses, as the backend declares them. */
const PORTS: Record<string, { inputs: string[]; outputs: string[] }> = {
  Start: { inputs: [], outputs: ['trigger'] },
  TensorCreate: { inputs: [], outputs: ['tensor'] },
  ScalarMultiply: { inputs: ['tensor'], outputs: ['tensor'] },
  Add: { inputs: ['tensor_a', 'tensor_b'], outputs: ['tensor'] },
  Mean: { inputs: ['tensor'], outputs: ['tensor'] },
};

function definitionFor(type: string): NodeDefinition {
  const spec = PORTS[type] ?? { inputs: [], outputs: [] };
  return {
    node_name: type,
    category: 'x',
    description: '',
    inputs: spec.inputs.map((name) => ({
      name, data_type: 'TENSOR', description: '', optional: false,
    })),
    outputs: spec.outputs.map((name) => ({
      name, data_type: name === 'trigger' ? 'TRIGGER' : 'TENSOR',
      description: '', optional: false,
    })),
    params: [],
  };
}

function toCanvas(raw: any[]): Node<NodeData>[] {
  return raw.map((n) => ({
    id: n.id,
    type: n.type === 'Start' ? 'start' : 'baseNode',
    position: n.position,
    data: {
      label: n.id,
      type: n.type,
      params: n.data?.params ?? {},
      definition: definitionFor(n.type),
      executionStatus: 'idle' as const,
    },
  }));
}

function toCanvasEdges(raw: any[]): Edge[] {
  return raw.map((e) =>
    e.type === 'trigger'
      ? {
          id: e.id, source: e.source, target: e.target,
          sourceHandle: e.sourceHandle, targetHandle: e.targetHandle,
          type: 'triggerEdge', data: { type: 'trigger' },
        }
      : {
          id: e.id, source: e.source, target: e.target,
          sourceHandle: e.sourceHandle, targetHandle: e.targetHandle,
        },
  );
}

const store = () => useTabStore.getState();

/**
 * Compare nodes/edges by CONTENT, not by the order they happen to come out in.
 *
 * Node and edge order carries no meaning to either side -- the engine keys
 * everything by id -- so pinning it would fail the contract for a harmless
 * reordering inside `collapseSelection`. Definition LISTS are deliberately NOT
 * sorted anywhere below: `subgraphs` order is the one ordering that is a real
 * behavioural fact -- `sameSubgraphs` compares the two lists INDEX BY INDEX, so
 * a reordering is a change as far as the store is concerned, and it is what
 * decides whether leaving a sub-canvas records an undo entry. That comparison
 * stays order-sensitive on purpose.
 */
const sortById = (rows: any[]) =>
  [...rows].sort((a, b) => String(a.id).localeCompare(String(b.id)));

beforeEach(() => {
  useTabStore.setState({ tabs: [], activeTabId: null as unknown as string });
  store().addTab('contract');
});

describe('subgraph collapse contract', () => {
  it('produces exactly the collapsed graph the backend suite executes', () => {
    const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));

    store().setNodes(toCanvas(fixture.flat.nodes));
    store().setEdges(toCanvasEdges(fixture.flat.edges));

    // The pure collapse with the fixture's ids pinned; everything else --
    // boundary derivation, rewiring, serialization -- is the shipped path.
    const result = collapseSelection(
      store().getActiveTab().nodes,
      store().getActiveTab().edges,
      [],
      fixture.selection,
      { id: fixture.subgraphId, instanceId: fixture.instanceId, name: fixture.name },
    );
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    store().setNodes(result.nodes);
    store().setEdges(result.edges);
    store().setSubgraphs(result.subgraphs);

    const serialized = JSON.parse(JSON.stringify(store().getSerializedGraph()));

    // Regenerate the fixture with
    //   CODEFYUI_WRITE_SUBGRAPH_FIXTURE=1 pnpm exec vitest run \
    //     src/utils/subgraph.contract.test.ts
    // then re-run the backend suite: the point of the file is that the two
    // halves execute alike, so a regenerated fixture is only correct once
    // `backend/tests/test_subgraph_contract.py` has agreed with it.
    if (process.env.CODEFYUI_WRITE_SUBGRAPH_FIXTURE) {
      fixture.collapsed = {
        nodes: serialized.nodes,
        edges: serialized.edges,
        subgraphs: serialized.subgraphs,
      };
      writeFileSync(FIXTURE, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
    }

    expect(sortById(serialized.nodes)).toEqual(sortById(fixture.collapsed.nodes));
    expect(sortById(serialized.edges)).toEqual(sortById(fixture.collapsed.edges));
    expect(serialized.subgraphs).toEqual(fixture.collapsed.subgraphs);

    // This selection must keep CROSSING A TRIGGER BOUNDARY.
    //
    // The trigger fan-out is the most intricate rewrite in the feature -- one
    // side mints a `-sg` edge to the instance at collapse, the other replicates
    // it to every declared inner target with a `#n` suffix at expansion -- and
    // it is the one part the cross-layer artifact nearly failed to cover: the
    // selection used to be `[m1, m2, sum]`, none of which Start triggers, so
    // `triggerTargets` came out `[]` and the whole rewrite was exercised only
    // by each side's own unit tests. Two suites that never meet agree with each
    // other and with nothing else, which is precisely the arrangement this
    // shared file exists to replace.
    //
    // Asserted on `serialized`, not on the fixture, so it fires even on a
    // regeneration run -- narrowing `selection` back to a trigger-free set and
    // rewriting the file would otherwise pass silently, both halves agreeing on
    // a graph that no longer covers anything.
    const definition = serialized.subgraphs[0];
    expect(definition.interface.triggerTargets.length).toBeGreaterThan(0);
    expect(fixture.selection).toEqual(
      expect.arrayContaining(definition.interface.triggerTargets),
    );
    expect(
      serialized.edges.filter(
        (e: any) =>
          e.type === 'trigger' &&
          e.target === fixture.instanceId &&
          e.targetHandle === '__trigger',
      ),
    ).toHaveLength(1);

    // ...and it must keep exercising BOUNDARY PORT NAME DEDUPLICATION.
    //
    // `m1` and `m2` both leave the block on a handle called `tensor`, so the
    // second one has to be renamed -- two ports of one name would be a block
    // whose second output is unaddressable. That rename is not a cosmetic
    // detail: `port` is the only name the outer edge carries, and expansion
    // looks it up in the interface to decide which INNER node the edge really
    // comes from. Getting it wrong swaps which multiply feeds which side of
    // the Add.
    //
    // It belongs here rather than in a unit test because the two sides have to
    // agree on the generated name. Execution equivalence cannot referee that:
    // the consumer is an Add, and 10 + 21 == 21 + 10, so a swapped mapping
    // still computes 31. `test_subgraph_contract.py` pins the routing those
    // names produce; this pins the names themselves.
    expect(definition.interface.outputs.map((p: any) => p.port)).toEqual([
      'tensor',
      'tensor_2',
    ]);
    expect(definition.interface.outputs.map((p: any) => p.innerNode)).toEqual([
      'm1',
      'm2',
    ]);
  });

  it('collapses a 60-node demo into four boxes', () => {
    // Acceptance criterion 3. Four independent branches of thirteen
    // multiplies each, summed at the end; every branch's chain becomes one
    // block. The backend suite runs the result and checks the number.
    const nodes: any[] = [
      { id: 'start', type: 'Start', position: { x: 0, y: 0 }, data: { params: {} } },
    ];
    const edges: any[] = [];
    const branchTails: string[] = [];
    const groups: string[][] = [];

    for (let branch = 0; branch < 4; branch += 1) {
      const y = branch * 200;
      const root = `src${branch}`;
      nodes.push({
        id: root, type: 'TensorCreate', position: { x: 100, y },
        data: { params: { shape: '1,2', fill: 'full', value: branch + 1 } },
      });
      edges.push({
        id: `t${branch}`, source: 'start', target: root,
        sourceHandle: 'trigger', targetHandle: '__trigger', type: 'trigger',
      });
      const chain: string[] = [];
      let previous = root;
      let previousPort = 'tensor';
      for (let step = 0; step < 13; step += 1) {
        const id = `b${branch}m${step}`;
        nodes.push({
          id, type: 'ScalarMultiply',
          position: { x: 220 + step * 90, y },
          data: { params: { scalar: 1 } },
        });
        edges.push({
          id: `e${branch}_${step}`, source: previous, target: id,
          sourceHandle: previousPort, targetHandle: 'tensor',
        });
        chain.push(id);
        previous = id;
        previousPort = 'tensor';
      }
      groups.push(chain);
      branchTails.push(previous);
    }

    // 4 branches -> 3 Adds: 1 + 4*(1 + 13) + 3 = 60 nodes.
    let running = branchTails[0];
    for (let index = 1; index < 4; index += 1) {
      const id = `sum${index}`;
      nodes.push({
        id, type: 'Add', position: { x: 1500, y: index * 200 },
        data: { params: { alpha: 1 } },
      });
      edges.push({
        id: `sa${index}`, source: running, target: id,
        sourceHandle: 'tensor', targetHandle: 'tensor_a',
      });
      edges.push({
        id: `sb${index}`, source: branchTails[index], target: id,
        sourceHandle: 'tensor', targetHandle: 'tensor_b',
      });
      running = id;
    }
    expect(nodes).toHaveLength(60);

    store().setNodes(toCanvas(nodes));
    store().setEdges(toCanvasEdges(edges));

    groups.forEach((chain, index) => {
      const current = store().getActiveTab();
      const result = collapseSelection(
        current.nodes, current.edges, current.subgraphs, chain,
        { id: `blk${index}`, instanceId: `inst${index}`, name: `Branch ${index}` },
      );
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      store().setNodes(result.nodes);
      store().setEdges(result.edges);
      store().setSubgraphs(result.subgraphs);
    });

    const serialized = JSON.parse(JSON.stringify(store().getSerializedGraph()));
    expect(serialized.subgraphs).toHaveLength(4);
    expect(
      serialized.nodes.filter((n: any) => String(n.type).startsWith('subgraph:')),
    ).toHaveLength(4);
    // 60 nodes minus the 52 that moved inside, plus 4 boxes.
    expect(serialized.nodes).toHaveLength(12);

    // Re-read rather than reuse the object the first test parsed: that test
    // has already written its own half back, and holding a stale parse here
    // would write the pre-collapse `collapsed` straight back over it.
    const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));
    if (process.env.CODEFYUI_WRITE_SUBGRAPH_FIXTURE) {
      fixture.demo60 = {
        flat: { nodes, edges },
        collapsed: {
          nodes: serialized.nodes,
          edges: serialized.edges,
          subgraphs: serialized.subgraphs,
        },
      };
      writeFileSync(FIXTURE, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
    }

    // The counts above are the ACCEPTANCE CRITERION ("60 nodes become 4
    // boxes"); what follows is the CONTRACT. Without it this half of the
    // fixture -- roughly 2,800 of its ~3,000 lines -- is an unchecked
    // snapshot: the backend keeps executing whatever was written the last
    // time someone set the env var, and any later change to collapse silently
    // makes the executed graph something the editor no longer produces. A
    // reviewer proved the hole by flipping `collapseSelection`'s definition
    // accumulation to `[definition, ...subgraphs]` -- a real change to the
    // order blocks are recorded in across sequential collapses -- and both
    // tests here stayed green.
    //
    // The FLAT half is pinned too, even though this test builds it itself.
    // The loop above is the generator and the stored copy is what the backend
    // actually runs; nothing else notices if the two drift, and once they do
    // "the collapsed graph computes what the flat one computes" is a claim
    // about two different graphs.
    expect(sortById(nodes)).toEqual(sortById(fixture.demo60.flat.nodes));
    expect(sortById(edges)).toEqual(sortById(fixture.demo60.flat.edges));
    expect(sortById(serialized.nodes)).toEqual(
      sortById(fixture.demo60.collapsed.nodes),
    );
    expect(sortById(serialized.edges)).toEqual(
      sortById(fixture.demo60.collapsed.edges),
    );
    expect(serialized.subgraphs).toEqual(fixture.demo60.collapsed.subgraphs);
  });
});
