import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the docs/ folder structure. Ordering and labels
// for each category come from the `_category_.json` files in each subfolder and
// the `sidebar_position` front-matter on each page.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
